### ISSUE TITLE
Enhancement suggestion: Hide or disable the backup item in the main menu for certain roles

### ISSUE THREAD

**Issue by vauvarin** [sylvainjule/kirby-backups#2]
It would be great to be able to hide or disable the backup item in the main menu for certain roles.

**Comment by sylvainjule** [comment]
I just tested it and it actually works out of the box with permissions 🎉

```yml
# site/blueprints/users/*.yml
permissions:
  access:
    backups: false
```

Will disable the button.

By default, disabled dropdown items are faded. If you need to hide them completely:

```css
.k-topbar-menu .k-dropdown-item[data-disabled] {
    display: none;
}
```
